### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by GreenMatthew2019** [a-b-street/abstreet#1122]
I have down loaded the software (for Mac) and run the ltn.exe 
I now have a terminal window open.
what do I do next to get started?

**Comment by dabreegster** [comment]
I don't have a Windows or Mac machine myself to test on, so starting the software there is unfortunately broken. Try opening the `ltn` executable inside the `binaries` folder -- does that do anything?

**Comment by GreenMatthew2019** [comment]
Hi,
Thanks for the quick reply. 
That’s what I did.
Opened binaries folder,
Ran ltn.exe

Terminal opened window as below

Last login: Mon Oct  9 12:32:41 on ttys000
/Users/matthewsnedker/Downloads/abstreet_mac_v0_3_48/binaries/ltn ; exit;
***@***.*** ~ % /Users/matthewsnedker/Downloads/abstreet_mac_v0_3_48/binaries/ltn ; exit;
thread 'main' panicked at 'Can't find the data/ directory', abstio/src/abst_paths.rs:54:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Note: the data folder is in my downloads folder.

**Comment by dabreegster** [comment]
Sorry, I'm not sure how to fix this without access to a Mac to try things out. This is an open source project; if anyone's reading this and can help get the Windows and Mac builds working better, help much appreciated.

In the meantime, stick with the web version: https://play.abstreet.org/0.3.48/ltn.html    and let me know if you need a new area imported (not possible on the web version, unfortunately)

**Comment by dabreegster** [comment]
I can at least get that area added to the web version today. The image in your email didn't come through to Github; does this cover it?
![Screenshot from 2023-10-09 13-00-44](https://github.com/a-b-street/abstreet/assets/1664407/7f66405e-61e3-477f-9ff5-741c682330cb)

**Comment by GreenMatthew2019** [comment]
Definitely covers the area I’m looking to improve. Thank you. Matthew Sent from my iPhoneOn 9 Oct 2023, at 13:01, Dustin Carlino ***@***.***> wrote:﻿
I can at least get that area added to the web version today. The image in your email didn't come through to Github; does this cover it?

**Comment by dabreegster** [comment]
Try this out and let me know if you hit problems: https://play.abstreet.org/0.3.48/ltn.html?system/gb/darlington/maps/center.bin

**Comment by andrewphilipsmith** [comment]
I think I can reproduce this. The behaviour I find is:

* If  the current working directory is inside the the expanded zip file (typically `abstreet_mac_v0_3_48`) then the binary launches correctly.
* If `cwd` is a directory outside the expanded zip file, then launching the binary will fail.

## How to reproduce

1. Download https://github.com/a-b-street/abstreet/releases/download/v0.3.48/abstreet_mac_v0_3_48.zip and save in to the default `Downloads` directory.
2. Unzip by double clicking. This will expand the zipfile into a `Downloads/abstreet_mac_v0_3_48` directory.
3. Open a terminal. The default `cwd` is the user's home directory
4. Attempt to launch one of the applications, either directly from the binary, or via the wrapper shell scripts

```bash
user@host ~$ Downloads/abstreet_mac_v0_3_48/binaries/ltn                                                                                        127 
thread 'main' panicked at 'Can't find the data/ directory', abstio/src/abst_paths.rs:54:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@host ~$ Downloads/abstreet_mac_v0_3_48/ltn.sh                                                                                              101 ↵  
See logs in output.txt
```

_(Untested, but I suspect that the same baviour would occur on Windows and Linux)_

## Workaround

1. Change directory in the terminal to the expanded zip directory:

```bash
user@host ~$ cd Downloads/abstreet_mac_v0_3_48
```
(Note that your prompt might look different to the above - ie everything before and including the `$` sign)

2. Launch the app:

```
user@host ~/Downloads/abstreet_mac_v0_3_48$ binaries/ltn      
```

@GreenMatthew2019 Please could you let us know if this workaround helps you? Feel free to ask if you've any other questions.

## Possible fixes

@dabreegster Some ideas for longer-term fixes:

* We could make the wrapper scripts more robust, by detecting their own location, rather than assuming that the `cwd` is correct (See Mac/Linux https://stackoverflow.com/a/59916, Windows https://ss64.com/nt/syntax-args.html)
* We could improve the search for the data directory. I think at present if uses the `cwd`, rather than the binary location as the start point for its search
* We could improve the error message, when it fail to find the data fdir, to be more actionable.

**Comment by dabreegster** [comment]
Fantastic debugging + write-up, thank you!

> We could improve the search for the data directory

https://github.com/a-b-street/abstreet/blob/f8e5d5f0a5f087f5038c309319ce9a50ac895a26/abstio/src/abst_paths.rs#L22
Rather than use the current directory as the base, we could try https://doc.rust-lang.org/std/env/fn.current_exe.html after stripping off the executable?

The variations of `../`, `../../`, etc in there are so that you can launch tools from different cases in the release binaries, from git, etc. For example `cd abstreet/apps/ltn/src; cargo run` would require us to find `../../data`. Maybe there's a much saner way to do this though?

> We could make the wrapper scripts more robust, by detecting their own location

This sounds useful. If somebody directly opens the exe, it'd still break, but be an improvement.

**Comment by ciaosamuu** [comment]
Hello, I'm completely aware that it's been two years since the discussion started although the problem still persists to me (also mainly because I'm not familiar with terminals, codes etc...). I tried all the suggestions, but I still can't open it
