### ISSUE TITLE
Crash when converting stopsign intersection to traffic light intersection in Task 8 of tutorial.

### ISSUE THREAD

**Issue by evanj97** [a-b-street/abstreet#649]
As the title says.  when converting the intersection of Boyer Avenue East and 15th Avenue East from a stop-sign intersection to a traffic light intersection.  I was able to repeat this multiple times in Task 8 of the game tutorial.

edit:  included edits_during_crash.json (zipped up for github)

<img width="1591" alt="Task 8" src="https://user-images.githubusercontent.com/45179103/118375568-359ab880-b577-11eb-9890-31cf5a9740c2.png">

[edits_during_crash.zip](https://github.com/a-b-street/abstreet/files/6488084/edits_during_crash.zip)

**Comment by evanj97** [comment]
```

- load scenario took 0.0072s
    - BorderSpawnOverTime (1)... 0.0000s
    - ... plus 0.0003s
  - ... plus 0.0068s
instantiate scenario...
Instantiating car vs bike contention...
trips for People (20)... 0.0003s
spawn trips (20)... 0.0003s
Instantiating car vs bike contention... plus 0.0419s
Instantiating car vs bike contention took 0.0425s
instantiate scenario... plus 0.0063s
instantiate scenario took 0.0488s

- instantiate scenario took 0.0488s
  - Instantiating car vs bike contention took 0.0425s
    - trips for People (20)... 0.0003s
    - spawn trips (20)... 0.0003s
    - ... plus 0.0419s
  - ... plus 0.0063s
apply map edits...
generate unzoomed roads and intersections...
generate unzoomed roads and intersections took 0.0403s
Wrote data/player/edits/us/seattle/montlake/Untitled Proposal 4.json
apply map edits... plus 0.0109s
apply map edits took 0.0512s

- apply map edits took 0.0512s
  - generate unzoomed roads and intersections took 0.0403s
  - ... plus 0.0109s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: exact_slice(1.4m, 0.5134m) yielded empty slice

Caused by:
    Can't get a polyline slice [1.4m, 0.5134m]', geom\src\polyline.rs:280:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

********************************************************************************
Wrote data/player/camera_state/us/seattle/montlake.json
Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 6236.052520046968, "cam_y": 7520.749318134204, "cam_zoom": 10.374969840400013 }

Wrote edits_during_crash.json
Please include edits_during_crash.json in your bug report.

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
error: process didn't exit successfully: `target\debug\game.exe` (exit code: 101)

```

**Comment by dabreegster** [comment]
Running with `RUST_BACKTRACE=1 gives more hints:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: exact_slice(1.4m, 0.5134m) yielded empty slice
                      
Caused by:            
    Can't get a polyline slice [1.4m, 0.5134m]', geom/src/polyline.rs:280:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/result.rs:1037:23
   4: geom::polyline::PolyLine::exact_slice
             at /home/dabreegster/abstreet/geom/src/polyline.rs:280:9
   5: map_gui::render::turn::DrawMovement::for_i
             at /home/dabreegster/abstreet/map_gui/src/render/turn.rs:51:21
```

https://github.com/a-b-street/abstreet/blob/56b16f8daea875a838ea03a33cf67c3e4dfc30c4/map_gui/src/render/turn.rs#L51 is the problem. `pl` is a poly-line (line-string) representing some movement across the intersection. `exact_slice` takes 2 `Distances`, but the first one is somehow winding up to be larger than the second.
