### ISSUE TITLE
Panic (unwapping None) in game::edit::roads::highlight_current_selection

### ISSUE THREAD

**Issue by Anaphory** [a-b-street/abstreet#703]
I got this panic when trying to select an ultra-short road between two big intersections in order to add lanes to it.

```
- create blank sim took 0.0833s
  - setup offstreet parking (33,020)... 0.0056s
  - ... plus 0.0777s
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', game/src/edit/roads.rs:662:18
stack backtrace:
   0:     0x55d73a6cf760 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d73a6cf760 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d73a6cf760 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d73a6cf760 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d73a6f6e9f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55d73a6c9185 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55d73a6d19cb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d73a6d19cb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d73a6d19cb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55d73a6d149d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55d73a6d1fdd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55d73a6d1b47 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x55d73a6cfbfc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d73a6d1ad9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55d73978d4c1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55d73978d40d - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x55d739b0eadd - game::edit::roads::highlight_current_selection::h83cd209f4d85ab71
  17:     0x55d739b08bc5 - game::edit::roads::RoadEditor::recalc_all_panels::ha12a82b70fb243c7
  18:     0x55d739b0dc87 - <game::edit::roads::RoadEditor as widgetry::app_state::State<game::app::App>>::event::hab98ac271b536714
  19:     0x55d7399f07c5 - widgetry::app_state::App<A>::event::ha9046bba625abe8b
  20:     0x55d739baf875 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h02c70accc15f011e
  21:     0x55d7397beba7 - widgetry::runner::State<A>::event::h7e07eb98a66c9006
  22:     0x55d7399897e0 - widgetry::runner::run::{{closure}}::ha7fe3f74da4859c2
  23:     0x55d739985d18 - winit::platform_impl::platform::sticky_exit_callback::h34cb3b077c5de051
  24:     0x55d739a74148 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h0365a978e9151042
  25:     0x55d7399e3ede - winit::platform_impl::platform::x11::EventLoop<T>::run::h4a0733f1be28e2c2
  26:     0x55d739985bd8 - winit::platform_impl::platform::EventLoop<T>::run::h4c309c830a402ec3
  27:     0x55d7397ba1b0 - winit::event_loop::EventLoop<T>::run::hf91145b0fca957be
  28:     0x55d7397c0233 - widgetry::runner::run::h3a54de2ea6942c0a
  29:     0x55d7397ea3d1 - game::main::h2e5f65c883d54335
  30:     0x55d73978dd53 - std::sys_common::backtrace::__rust_begin_short_backtrace::he781d369be738e43
  31:     0x55d73978dd69 - std::rt::lang_start::{{closure}}::h0795c1e42c063359
  32:     0x55d73a6d24da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  33:     0x55d73a6d24da - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  34:     0x55d73a6d24da - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  35:     0x55d73a6d24da - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  36:     0x55d73a6d24da - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  37:     0x55d73978dd42 - main
  38:     0x7fc9c5d46b25 - __libc_start_main
  39:     0x55d73978dc3e - _start
  40:                0x0 - <unknown>

********************************************************************************
[2021-07-16T19:29:36Z INFO  abstio::io_native] Wrote data/player/camera_state/de/Osnabrueck/boundary.json
[2021-07-16T19:29:36Z INFO  abstio::io_native] Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 924868.4253715044, "cam_y": 767282.9270152531, "cam_zoom": 110.89177990369392 }

[2021-07-16T19:29:36Z INFO  abstio::io_native] Wrote edits_during_crash.json
Please include edits_during_crash.json in your bug report.

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```

**Comment by dabreegster** [comment]
Thanks for reporting! Those short roads never stop causing problems. This fix should at least avoid crashig. It'll be in this Sunday's build.
