### ISSUE TITLE
Another Panic

### ISSUE THREAD

**Issue by Anaphory** [a-b-street/abstreet#707]
This one occurred after selecting a stop-sign intersection and cilcking ‘edit stop sign’
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', game/src/edit/stop_signs.rs:47:76
stack backtrace:
   0:     0x557d171cb760 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x557d171cb760 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557d171cb760 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557d171cb760 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x557d171f2e9f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x557d171c5185 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x557d171cd9cb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557d171cd9cb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557d171cd9cb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x557d171cd49d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x557d171cdfdd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x557d171cdb47 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x557d171cbbfc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x557d171cdad9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x557d162894c1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x557d1628940d - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x557d16325d7d - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h4d75492fecbfb7ba
  17:     0x557d1628deea - <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::hc00d4978eee379bb
  18:     0x557d16732044 - game::edit::stop_signs::StopSignEditor::new_state::h43c109d354f5d9a3
  19:     0x557d165a7b6f - <game::sandbox::Actions as game::info::ContextualActions>::execute::heb9045547ee6ab7d
  20:     0x557d1673b12f - game::info::InfoPanel::event::hcd83311d442b6b7a
  21:     0x557d165f8694 - game::common::CommonState::event::hc40002c069e1ba3f
  22:     0x557d165a6373 - <game::sandbox::SandboxMode as widgetry::app_state::State<game::app::App>>::event::hbe91e87a7535f0a7
  23:     0x557d164ec7c5 - widgetry::app_state::App<A>::event::ha9046bba625abe8b
  24:     0x557d166ab875 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h02c70accc15f011e
  25:     0x557d162baba7 - widgetry::runner::State<A>::event::h7e07eb98a66c9006
  26:     0x557d164857e0 - widgetry::runner::run::{{closure}}::ha7fe3f74da4859c2
  27:     0x557d16481d18 - winit::platform_impl::platform::sticky_exit_callback::h34cb3b077c5de051
  28:     0x557d16570148 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h0365a978e9151042
  29:     0x557d164dfede - winit::platform_impl::platform::x11::EventLoop<T>::run::h4a0733f1be28e2c2
  30:     0x557d16481bd8 - winit::platform_impl::platform::EventLoop<T>::run::h4c309c830a402ec3
  31:     0x557d162b61b0 - winit::event_loop::EventLoop<T>::run::hf91145b0fca957be
  32:     0x557d162bc233 - widgetry::runner::run::h3a54de2ea6942c0a
  33:     0x557d162e63d1 - game::main::h2e5f65c883d54335
  34:     0x557d16289d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::he781d369be738e43
  35:     0x557d16289d69 - std::rt::lang_start::{{closure}}::h0795c1e42c063359
  36:     0x557d171ce4da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  37:     0x557d171ce4da - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  38:     0x557d171ce4da - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  39:     0x557d171ce4da - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  40:     0x557d171ce4da - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  41:     0x557d16289d42 - main
  42:     0x7f4169995b25 - __libc_start_main
  43:     0x557d16289c3e - _start
  44:                0x0 - <unknown>

********************************************************************************
[2021-07-18T15:12:57Z INFO  abstio::io_native] Wrote data/player/camera_state/de/Osnabrueck/boundary.json
[2021-07-18T15:12:57Z INFO  abstio::io_native] Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 161932.1344342235, "cam_y": 133792.99580460967, "cam_zoom": 19.487171000003126 }

[2021-07-18T15:12:57Z INFO  abstio::io_native] Wrote edits_during_crash.json
Please include edits_during_crash.json in your bug report.

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```

**Comment by dabreegster** [comment]
Thanks! I really need to fuzz test the editing UI. This is another problem from super short roads.
