### ISSUE TITLE
Don't Panic!

### ISSUE THREAD

**Issue by Anaphory** [a-b-street/abstreet#708]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', game/src/edit/stop_signs.rs:47:76
stack backtrace:
   0:     0x55df4c08a760 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55df4c08a760 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55df4c08a760 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55df4c08a760 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55df4c0b1e9f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55df4c084185 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55df4c08c9cb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55df4c08c9cb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55df4c08c9cb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55df4c08c49d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55df4c08cfdd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55df4c08cb47 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x55df4c08abfc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55df4c08cad9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55df4b1484c1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55df4b14840d - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x55df4b1e4d7d - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h4d75492fecbfb7ba
  17:     0x55df4b14ceea - <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::hc00d4978eee379bb
  18:     0x55df4b5f1044 - game::edit::stop_signs::StopSignEditor::new_state::h43c109d354f5d9a3
  19:     0x55df4b4cfef0 - <game::edit::EditMode as widgetry::app_state::State<game::app::App>>::event::hf7a7670a0b8fdc9a
  20:     0x55df4b3ab7c5 - widgetry::app_state::App<A>::event::ha9046bba625abe8b
  21:     0x55df4b56a875 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h02c70accc15f011e
  22:     0x55df4b179ba7 - widgetry::runner::State<A>::event::h7e07eb98a66c9006
  23:     0x55df4b3447e0 - widgetry::runner::run::{{closure}}::ha7fe3f74da4859c2
  24:     0x55df4b340d18 - winit::platform_impl::platform::sticky_exit_callback::h34cb3b077c5de051
  25:     0x55df4b42f148 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h0365a978e9151042
  26:     0x55df4b39eede - winit::platform_impl::platform::x11::EventLoop<T>::run::h4a0733f1be28e2c2
  27:     0x55df4b340bd8 - winit::platform_impl::platform::EventLoop<T>::run::h4c309c830a402ec3
  28:     0x55df4b1751b0 - winit::event_loop::EventLoop<T>::run::hf91145b0fca957be
  29:     0x55df4b17b233 - widgetry::runner::run::h3a54de2ea6942c0a
  30:     0x55df4b1a53d1 - game::main::h2e5f65c883d54335
  31:     0x55df4b148d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::he781d369be738e43
  32:     0x55df4b148d69 - std::rt::lang_start::{{closure}}::h0795c1e42c063359
  33:     0x55df4c08d4da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  34:     0x55df4c08d4da - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  35:     0x55df4c08d4da - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  36:     0x55df4c08d4da - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  37:     0x55df4c08d4da - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  38:     0x55df4b148d42 - main
  39:     0x7f3c54906b25 - __libc_start_main
  40:     0x55df4b148c3e - _start
  41:                0x0 - <unknown>

********************************************************************************
[2021-07-19T11:05:37Z INFO  abstio::io_native] Wrote data/player/camera_state/de/Osnabrueck/boundary.json
[2021-07-19T11:05:37Z INFO  abstio::io_native] Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 177156.68945091547, "cam_y": 160612.37875211285, "cam_zoom": 21.435888100001396 }

[2021-07-19T11:05:37Z INFO  abstio::io_native] Wrote edits_during_crash.json
Please include edits_during_crash.json in your bug report.

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```

**Comment by Anaphory** [comment]
Just scrolling around:
```
thread 'main' panicked at 'no entry found for key', map_model/src/map.rs:266:10
stack backtrace:
   0:     0x55a719ed5760 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a719ed5760 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a719ed5760 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a719ed5760 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a719efce9f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55a719ecf185 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55a719ed79cb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a719ed79cb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a719ed79cb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55a719ed749d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55a719ed7fdd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55a719ed7b77 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x55a719ed5bfc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a719ed7ad9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55a718f934c1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55a718f933b3 - core::option::expect_failed::h128888968e00dc4d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
  16:     0x55a719adcce9 - map_model::map::<impl map_model::Map>::get_l::ha0677697d21fe138
  17:     0x55a71950ff09 - map_gui::render::intersection::DrawIntersection::stop_sign_geom::h04eb8c5e38453c9a
  18:     0x55a719511106 - <map_gui::render::intersection::DrawIntersection as map_gui::render::Renderable>::draw::hd7fc3cf79e016072
  19:     0x55a718fc9830 - game::app::App::draw::he290f82a8f92143c
  20:     0x55a7191f6619 - widgetry::app_state::App<A>::draw::he644e16887ebe42d
  21:     0x55a718fc4845 - widgetry::runner::State<A>::draw::h8dd6a2996c3f17ab
  22:     0x55a71918f843 - widgetry::runner::run::{{closure}}::ha7fe3f74da4859c2
  23:     0x55a7191ea12d - winit::platform_impl::platform::x11::EventLoop<T>::run::h4a0733f1be28e2c2
  24:     0x55a71918bbd8 - winit::platform_impl::platform::EventLoop<T>::run::h4c309c830a402ec3
  25:     0x55a718fc01b0 - winit::event_loop::EventLoop<T>::run::hf91145b0fca957be
  26:     0x55a718fc6233 - widgetry::runner::run::h3a54de2ea6942c0a
  27:     0x55a718ff03d1 - game::main::h2e5f65c883d54335
  28:     0x55a718f93d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::he781d369be738e43
  29:     0x55a718f93d69 - std::rt::lang_start::{{closure}}::h0795c1e42c063359
  30:     0x55a719ed84da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  31:     0x55a719ed84da - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  32:     0x55a719ed84da - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  33:     0x55a719ed84da - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  34:     0x55a719ed84da - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  35:     0x55a718f93d42 - main
  36:     0x7fe60ef1db25 - __libc_start_main
  37:     0x55a718f93c3e - _start
  38:                0x0 - <unknown>

********************************************************************************
[2021-07-19T11:25:36Z INFO  abstio::io_native] Wrote data/player/camera_state/de/Osnabrueck/boundary.json
[2021-07-19T11:25:36Z INFO  abstio::io_native] Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 55397.876144482354, "cam_y": 47144.26675415823, "cam_zoom": 6.830134553651048 }

[2021-07-19T11:25:36Z INFO  abstio::io_native] Wrote edits_during_crash.json
Please include edits_during_crash.json in your bug report.

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```
