### ISSUE TITLE
Panicked on freshly pulled osm data & Won't start in sandbox mode again after

### ISSUE THREAD

**Issue by cpwnd** [a-b-street/abstreet#717]
Thats part of the stackstrace I got after selecting a scenario on freshly pulled osm data, without any changes to the streets.

```
thread 'main' panicked at 'assertion failed: !commuter_borders.is_empty()', sim/src/make/activity_model.rs:122:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: sim::make::activity_model::<impl sim::make::generator::ScenarioGenerator>::proletariat_robot
   4: game::sandbox::gameplay::GameplayMode::scenario
   5: widgetry::event_ctx::EventCtx::loading_screen
   6: <game::sandbox::SandboxLoader as widgetry::app_state::State<game::app::App>>::event
   7: widgetry::app_state::App<A>::event
   8: widgetry::event_ctx::EventCtx::no_op_event
   9: widgetry::app_state::App<A>::event
  10: widgetry::event_ctx::EventCtx::no_op_event
  11: widgetry::app_state::App<A>::event
  12: widgetry::event_ctx::EventCtx::no_op_event
  13: widgetry::app_state::App<A>::event
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: widgetry::runner::State<A>::event
  16: widgetry::runner::run::{{closure}}
  17: winit::platform_impl::platform::sticky_exit_callback
  18: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
  19: winit::platform_impl::platform::x11::EventLoop<T>::run
  20: winit::platform_impl::platform::EventLoop<T>::run
  21: winit::event_loop::EventLoop<T>::run
  22: widgetry::runner::run
  23: game::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
dropping Timer during create people, due to panic?
```

Now after each restart, the same error will cause a panic, because it will start with the failed scenario and map data from the last session.

EDIT: After using the internal dev tool, I got another city configured and started successfully with another city.

Hope this helps!
Happy to help with more info if needed.

Thanks for the awesome project :)
Best Chris

**Comment by dabreegster** [comment]
Thanks for reporting this! The scenarios you picked assume the map has intersections on the border of the map, but it looks like the new Overpass import doesn't include ways that cross the map boundary. I made the scenario generators handle no borders existing, but the real fix is to include those ways in the Overpass query. Looking into this now.

**Comment by dabreegster** [comment]
The fixes will make it into the release later today
